apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-guestbook
  namespace: argocd #it's must
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: cluster2
        url: https://34.41.196.209
        foo: baz
  template:
    metadata:
      name: 'prod-guestbook'
      labels:
        foo: '{{.foo}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/premkumarpanchatcharam/prod-app.git'
        targetRevision: HEAD
        path: guestbook/guestbook-application
      destination:
        server: '{{.url}}'
        namespace: prod-guestbook
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
